version: '3.9'

services: 
  db:
    image: postgres
    restart: always
    environment:    
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: internal_notes
    volumes:
       - ./db:/data/postgres
    ports:
      - "5432:5432"
  app:
    build: .
    command: >
      sh -c "
        npm run typeorm -- migration:run -d ./src/database/dataSource.ts &&
        npm run seed &&
        npm run start"
    ports:
      - "8080:8080"
    volumes: 
      -  '.:/usr/src/app'
