version: '3.9'

services: 
  db:
    container_name: db
    image: postgres
    restart: always
    environment:    
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: internal_notes
    volumes:
       - ./db:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: app
    build: .
    command: >
      sh -c "
        npm run typeorm -- migration:run -d ./src/database/dataSource.ts &&
        npm run seed &&
        npm run start"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
